### ISSUE TITLE
exception on start - nexus 4 emulator

### ISSUE THREAD

**Issue by drdrej** [drdrej/android-spacerx-playground#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.touchableheroes.drafts.spacerx.spacerx, PID: 3601
                                                                                          java.lang.RuntimeException: Unable to instantiate application com.touchableheroes.drafts.spacerx.app.DOMBasedApp: java.lang.ClassNotFoundException: Didn't find class "com.touchableheroes.drafts.spacerx.app.DOMBasedApp" on path: DexPathList[[zip file "/data/app/com.touchableheroes.drafts.spacerx.spacerx-1/base.apk", zip file "/data/app/com.touchableheroes.drafts.spacerx.spacerx-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.touchableheroes.drafts.spacerx.spacerx-1/split_lib_slice_6_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
                                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
                                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.touchableheroes.drafts.spacerx.app.DOMBasedApp" on path: DexPathList[[zip file "/data/app/com.touchableheroes.drafts.spacerx.spacerx-1/base.apk", zip file "/data/app/com.touchableheroes.drafts.spacerx.spacerx-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.touchableheroes.drafts.spacerx.spacerx-1/split_lib_slice_6_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:980)
                                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
                                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526) 
                                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                                          	Suppressed: java.lang.ClassNotFoundException: com.touchableheroes.drafts.spacerx.app.DOMBasedApp
                                                                                              at java.lang.Class.classForName(Native Method)
                                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                              		... 13 more
                                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by drdrej** [comment]
*/build ordner gelöscht.
projekt neu gebaut.

emulator musste nicht neu gestartet werden
